EFwithASPMVC/Models/Entities/Abstracts/Entity.cs
namespace Application.Models.Entities.Abstracts
{
	public class Entity
	{
		public int id { get; set; }
		public DateTime CreatedTime { get; set; } = DateTime.Now;
		public DateTime UpdatedTime { get; set; } = DateTime.Now;
	}
}

EFwithASPMVC/Models/Entities/Concretes/Group.cs
using Application.Models.Entities.Abstracts;

namespace Application.Models.Entities.Concretes
{
	public class Group:Entity
	{
		public string? Name { get; set; }
		public string? Description { get; set; }


		//Navigation property
		public ICollection<Student>? Students { get; set; } 
	}
}

EFwithASPMVC/Models/Entities/Concretes/Student.cs
using Application.Models.Entities.Abstracts;


namespace Application.Models.Entities.Concretes
{
	public class Student:Entity
	{
		public string? FirstName { get; set;}
		public string? LastName { get; set;}
		public string? Email { get; set;}

		//Foreign key
		public int GroupId { get; set; }

		//Navigation property
		public Group Group { get; set; }	
	}
}

EFwithASPMVC/Models/ErrorViewModel.cs
namespace EFwithASPMVC.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

EFwithASPMVC/ViewModels/GroupViewModels/AllGroupsVM.cs
using Application.Models.Entities.Concretes;

namespace Application.ViewModels.GroupViewModels
{
	public class AllGroupsVM
	{
		public int Id { get; set; }	
		public string? Name { get; set; }
		public string? Description { get; set; }
		public List<Student>? Students { get; set; }
	}
}

EFwithASPMVC/ViewModels/GroupViewModels/CrreateGroupVM.cs
namespace Application.ViewModels.GroupViewModels
{
	public class CrreateGroupVM
	{
		public string? Name { get; set; }
		public string? Description { get; set; }
	}
}

EFwithASPMVC/ViewModels/GroupViewModels/EditGroupVM.cs
namespace Application.ViewModels.GroupViewModels
{
	public class EditGroupVM
	{
		public int Id { get; set; }	
		public string? Name { get; set; }
		public string? Description { get; set; }
	}
}

EFwithASPMVC/ViewModels/GroupViewModels/ReadGroupVM.cs
using Application.Models.Entities.Concretes;
using Application.ViewModels.StudentViewModels;

namespace Application.ViewModels.GroupViewModels
{
	public class ReadGroupVM
	{
		public int Id { get; set; }
		public string? Name { get; set; }
		public string? Description { get; set; }
		public List<StudentVM>? Students { get; set; }
	}
}

EFwithASPMVC/ViewModels/StudentViewModels/StudentVM.cs
namespace Application.ViewModels.StudentViewModels
{
	public class StudentVM
	{
		public int ID { get; set; }	
		public string? FirstName { get; set; }
		public string? LastName { get; set; }
		public string? Email { get; set; }
		public int GroupId { get; set; }

	}
}

EFwithASPMVC/Controllers/GroupController.cs
using Application.Models.Entities.Concretes;
using Application.Repositories.Abstracts;
using Application.ViewModels.GroupViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Application.Controllers
{
	public class GroupController : Controller
	{
		private IRepository<Group> _repository;
		public GroupController(IRepository<Group> repository)
		{
			_repository = repository;
			ViewBag.Groups=_repository.GetAll().Select(g=>g.id).ToList();
		}

		[HttpGet]
		public IActionResult AllGroups()
		{
			List<AllGroupsVM> allGroups = new();
			foreach (Group group in _repository.GetAll())
			{
				allGroups.Add(new()
				{
					Id = group.id,
					Name = group.Name,
					Description = group.Description,
					Students = group.Students!.ToList()
				});
			}

			return View(allGroups);
		}

		[HttpGet]
		public IActionResult CreateGroup()
		{
			return View();
		}


		public IActionResult CreateGroup(CrreateGroupVM newGroupVM)
		{
			if (newGroupVM != null)
			{
				Group newGroup = new Group() { Name = newGroupVM.Name, Description = newGroupVM.Description };
				_repository.Create(newGroup);
			}
			return RedirectToAction("AllGroups");
		}


		public IActionResult ReadGroup(int id)
		{
			Group group = _repository.GetyByID(id);
			if (group is not null)
			{
				ReadGroupVM readGroup = new()
				{
					Id = group.id,
					Name = group.Name,
					Description = group.Description,
					Students = new()
				};
				foreach (Student student in group.Students)
				{
					readGroup.Students.Add(
						new()
						{
							ID = student.id,
							FirstName = student.FirstName,
							LastName = student.LastName,
							Email = student.Email,
							GroupId = student.id,
						}
						);
				}
				return View(readGroup);
			}
			return RedirectToAction("AllGroups");
		}


		[HttpGet]
		public IActionResult EditGroup(int id)
		{
			EditGroupVM changingGroup = new()
			{
				Id = id,
			};
			return View(changingGroup);
		}
		[HttpPost]
		public IActionResult EditGroup(EditGroupVM changedGroup)
		{
			if (changedGroup != null)
			{
				Group updatingGroup = _repository.GetyByID(changedGroup.Id);
				if (updatingGroup != null)
				{
					updatingGroup.Name = changedGroup.Name;
					updatingGroup.Description = changedGroup.Description;
					_repository.Update(updatingGroup);
				}
			}
			return RedirectToAction("AllGroups");
		}
		public IActionResult DeleteGroup(int id)
		{
			_repository.Delete(id);
			return RedirectToAction("AllGroups");
		}
	}
}

EFwithASPMVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Application.Data;
using Application.Models.Entities.Concretes;
using Application.Repositories.Abstracts;
using Application.ViewModels.StudentViewModels;

namespace Application.Controllers
{
	public class StudentController : Controller
	{
		private readonly IRepository<Student> _repository;

		public StudentController(IRepository<Student> repository)
		{
			_repository = repository;
            
        }

		// GET: Students
		[HttpGet]
		public IActionResult AllStudents()
		{
			List<StudentVM> students = new();
			foreach (Student student in _repository.GetAll().ToList())
			{
				students.Add(new()
				{
					ID = student.id,
					FirstName = student.FirstName,
					LastName = student.LastName,
					Email = student.Email,
					GroupId = student.GroupId,
				});
			}
			return View(students);
		}

		public async Task<IActionResult> Details(int id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var student = _repository.GetyByID(id);
			if (student == null)
			{
				return NotFound();
			}
			StudentVM studentDeail = new()
			{
				ID = student.id,
				FirstName = student.FirstName,
				LastName = student.LastName,
				Email = student.Email,
				GroupId = student.GroupId
			};
			return View(studentDeail);
		}

		public IActionResult Create()
		{
            return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(StudentVM student)
		{
			if (ModelState.IsValid)
			{
				Student newStudent = new()
				{
					FirstName = student.FirstName,
					LastName = student.LastName,
					Email = student.Email,
					GroupId = student.GroupId
				};
				_repository.Create(newStudent);

				return RedirectToAction("AllStudents");
			}
			return View();
		}

		// GET: Students/Edit/5
		public IActionResult Edit(int id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var student = _repository.GetyByID(id);
			if (student == null)
			{
				return NotFound();
			}
			StudentVM updatingStudent = new()
			{
				ID = student.id,
				FirstName = student.FirstName,
				LastName = student.LastName,
				Email = student.Email,
				GroupId = student.GroupId
			};
			return View(updatingStudent);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(StudentVM student)
		{
			if (student == null)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				var updatingStudent = _repository.GetyByID(student.ID);
				updatingStudent.FirstName = student?.FirstName;
				updatingStudent.LastName = student?.LastName;
				updatingStudent.Email = student?.Email;
				updatingStudent.GroupId = student!.GroupId;
				_repository.Update(updatingStudent);
			}

			return RedirectToAction("AllStudents");
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(int id)
		{
			if (id != null)
			{
				_repository.Delete(id);
			}

			return RedirectToAction("AllStudents");
		}

		
	}
}

EFwithASPMVC/Views/Group/AllGroups.cshtml
@model List<AllGroupsVM>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Description</th>
			<th>Read</th>
			<th>Update</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		@foreach (AllGroupsVM group in Model)
		{
			<tr>
				<td>@group.Id</td>
				<td>@group.Name</td>
				<td>@group.Description</td>
				<td>
					<form asp-controller="Group" asp-action="ReadGroup">
						<input type="hidden" name="id" value="@group.Id" />
						<button type="submit" class="btn btn-primary btn-sm">Read</button>
					</form>
				</td>
				<td>
					<form method="get" asp-controller="Group" asp-action="EditGroup">
						<input name="id" type="hidden" value="@group.Id" />
						<button type="submit" class="btn btn-primary btn-sm">Update</button>
					</form>
				</td>
				<td>
					<form asp-controller="Group" asp-action="DeleteGroup">
						<input name="id" type="hidden" value="@group.Id" />
						<button type="submit" class="btn btn-danger btn-sm">Delete</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
</table>

EFwithASPMVC/Views/Group/CreateGroup.cshtml
@model CrreateGroupVM


<form method="post" asp-controller="Group" asp-action="CreateGroup" class="form-control">
    <div class="input-group mb-3">
        <span class="input-group-text" id="NameAddon">Name</span>
        <input type="text" id="Name" name="Name" class="form-control" asp-for="Name" aria-describedby="NameAddon" />
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="DescriptionAddon">Description</span>
        <input type="text" id="Description" name="Description" class="form-control" asp-for="Description" aria-describedby="DescriptionAddon" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

EFwithASPMVC/Views/Group/EditGroup.cshtml
@model EditGroupVM

<form method="post" asp-controller="Group" asp-action="EditGroup" class="form-control">
    <input type="hidden" asp-for="Id" />

    <div class="input-group mb-3">
        <span class="input-group-text" id="NameAddon">Name</span>
        <input type="text" id="Name" name="Name" class="form-control" asp-for="Name" aria-describedby="NameAddon" />
    </div>

    <div class="input-group mb-3">
        <span class="input-group-text" id="DescriptionAddon">Description</span>
        <input type="text" id="Description" name="Description" class="form-control" asp-for="Description" aria-describedby="DescriptionAddon" />
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

EFwithASPMVC/Views/Group/ReadGroup.cshtml
@model ReadGroupVM

<h2>@Model.Id</h2>
<h1>@Model.Name</h1>
<p>@Model.Description</p>

@if (Model.Students!.Any())
{
	<h2>Students</h2>
	<ul>
		@foreach (StudentVM student in Model.Students)
		{
			<li>
				<div>
					<h3>@student.FirstName - @student.LastName</h3>
					<h4>@student.Email</h4>
					<br />
				</div>
			</li>
		}
	</ul>
}
else
{
	<p>No students in this group.</p>
}

EFwithASPMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFwithASPMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFwithASPMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFwithASPMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="AllGroups">All Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="CreateGroup">Create group</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="AllStudents">All students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Create student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EFwithASPMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EFwithASPMVC/Views/Student/AllStudents.cshtml
@model List<StudentVM>

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				ID
			</th>
			<th>
				Firstname
			</th>
			<th>
				Lastname
			</th>
			<th>
				Email
			</th>
			<th>
				Group ID
			</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (StudentVM student in Model)
		{
			<tr>
				<td>
					@student.ID
				</td>
				<td>
					@student.FirstName
				</td>
				<td>
					@student.LastName
				</td>
				<td>
					@student.Email
				</td>
				<td>
					@student.GroupId
				</td>
				<td>
					<button class="btn-primary" type="submit" asp-action="Details" asp-route-id="@student.ID">Read</button>
				</td>
				<td>
					<form method="get" asp-action="Edit" asp-controller="Student">
						<input type="hidden" name="id" value="@student.ID" />
						<button type="submit" class="btn-primary">Update</button>
					</form>
				</td>
				<td>
					<form method="post" asp-action="Delete" asp-controller="Student">
						<input type="hidden" name="id" value="@student.ID" />
						<button type="submit" class="btn-primary">Delete</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
</table>

EFwithASPMVC/Views/Student/Create.cshtml
@model StudentVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <input type="number" asp-for="GroupId" class="form-control" >
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllStudents">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EFwithASPMVC/Views/Student/Details.cshtml
@model StudentVM

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>Student</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ID)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ID)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.FirstName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.FirstName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.LastName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.LastName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Email)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Email)
		</dd>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.GroupId)
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.ID">Update</a> |
	<a asp-action="AllStudents">Back to List</a>
</div>

EFwithASPMVC/Views/Student/Edit.cshtml
@model StudentVM

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<input type="hidden" asp-for="ID" />
			<div class="form-group">
				<label asp-for="FirstName" class="control-label"></label>
				<input asp-for="FirstName" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="LastName" class="control-label"></label>
				<input asp-for="LastName" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label>
				<input asp-for="Email" class="form-control" />
			</div>
			<div class="form-group">
				<label asp-for="GroupId" class="control-label"></label>
				<input type="number" asp-for="GroupId" class="form-control" />
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}